import assert from 'node:assert/strict';
import {simulate} from './battle-engine.js';
const ability=(id,kind='global')=>({id,name:id,definition:{kind,rules:[]}});
const mv=(id,targeting='single',category='physical',power=40,rules=[])=>({id,name:id,definition:{kind:id==='u'?'unique':'global',type:'fuego',category,power,accuracy:100,criticalChance:0,priority:0,cooldown:0,targeting,rules}});
const ent=(id,speed=100)=>({id,name:id,definition:{types:['fuego'],hp:100,attack:100,defense:100,specialAttack:100,specialDefense:100,speed,moveIds:['single','enemy','all'],uniqueMoveId:'u',globalAbilityId:'g',uniqueAbilityId:'gu'}});
const catalog={entities:Object.fromEntries(['a','b','c','d','e','f','g1','h'].map((id,i)=>[id,ent(id,100-i)])),moves:{single:mv('single'),enemy:mv('enemy','enemy_team'),all:mv('all','all'),u:mv('u','ally','status',0)},abilities:{g:ability('g'),gu:ability('gu','unique')},effects:{},statuses:{},weathers:{},fields:{},scenarios:{}};
const base={leftTeam:['a','b','c','d'],rightTeam:['e','f','g1','h'],left:'a',right:'e',catalog,chart:{fuego:{fuego:'neutral'}},mode:'doubles',randomSource:()=>.9};
let r=simulate({...base,turns:1,leftOrders:[{actions:[{slot:0,move:'enemy'},{slot:1,move:'u'}]}],rightOrders:[{actions:[{slot:0,move:'u'},{slot:1,move:'u'}]}]});
assert.ok(r.rightActive.every(x=>x.hp<100),'Equipo contrario golpea a ambos rivales');
assert.equal(r.leftActive[0].hp,100,'Equipo contrario no golpea aliados');
r=simulate({...base,turns:1,leftOrders:[{actions:[{slot:0,move:'all'},{slot:1,move:'u'}]}],rightOrders:[{actions:[{slot:0,move:'u'},{slot:1,move:'u'}]}]});
assert.ok(r.leftActive[1].hp<100&&r.rightActive.every(x=>x.hp<100),'Todos golpea compañero y ambos rivales');
r=simulate({...base,turns:1,leftOrders:[{actions:[{slot:0,move:'single',target:{side:'left',slot:1}},{slot:1,move:'u'}]}],rightOrders:[{actions:[{slot:0,move:'u'},{slot:1,move:'u'}]}]});
assert.ok(r.leftActive[1].hp<100,'Un objetivo admite fuego amigo');
assert.equal(r.rightActive[0].hp,100,'Un objetivo no golpea otro personaje');
const reduced=structuredClone(catalog);reduced.moves.enemy.definition.rules=[{event:'manual_doubles',condition:{type:'always',value:''},conditions:[],target:'self',action:{type:'damage_multiplier',value:50,stat:'',switchMode:'random'},chance:100,duration:0,limit:0,operator:'AND',negate:false}];
const normal=simulate({...base,turns:1,leftOrders:[{actions:[{slot:0,move:'enemy'},{slot:1,move:'u'}]}],rightOrders:[{actions:[{slot:0,move:'u'},{slot:1,move:'u'}]}]});
const half=simulate({...base,catalog:reduced,turns:1,leftOrders:[{actions:[{slot:0,move:'enemy'},{slot:1,move:'u'}]}],rightOrders:[{actions:[{slot:0,move:'u'},{slot:1,move:'u'}]}]});
assert.ok(half.rightActive[0].hp>normal.rightActive[0].hp,'Al usar en Doubles puede reducir daño mediante regla opcional');
console.log('PASS: doubles targets, friendly fire and configurable doubles damage');
