import assert from 'node:assert/strict';
import fs from 'node:fs';
const worker=fs.readFileSync(new URL('./worker.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('./public/editor/index.html',import.meta.url),'utf8');
assert.match(worker,/\/editor-api\/publish-alpha/);
assert.match(worker,/public-v1:snapshot:/);
assert.match(worker,/public-v1:current/);
assert.match(worker,/published\/\$\{revision\}\/sprites/);
assert.match(worker,/published\/\$\{revision\}\/type-icons/);
assert.match(worker,/Falta el sprite/);
assert.match(html,/id="publishAlpha"/);
assert.match(html,/Cargar parche al público/);
assert.match(html,/publishPatchStatus/);
console.log('manual public patch tests ok');
